
# Tidyverse를 활용한 데이터 다루기{#ch6}


## `tidyr`로 tidy 데이터 만들기

### 데이터 피벗: `pivot_longer()`와 `pivot_wider()`

### 문자형 열의 결합과 분리: `separate()`와 `unite()`


## `dplyr`에 의한 데이터 결합

## `stringr`에 의한 문자 다루기






# R에서의 프로그래밍{#chapter-programming}


## 사용자 정의 함수

### 함수의 정의

### 변수

### 변수 지정

### 결과의 출력

### 유효 범위


## 조건 연산

### 함수 `if()`에 의한 조건 연산

### 함수 `ifelse()`에 의한 조건 연산

### 함수 `switch()`에 의한 조건 연산


## 루프 연산

### for 루프

### while 루프


## 함수형 프로그래밍

## 함수형 프로그래밍으로 행렬과 데이터 프레임 다루기

## `purrr`에 의한 프로그래밍






# 확률분포{#chapter-distribution}

## R에서의 확률분포 이름


## 연속형 확률분포

### 정규분포

### 지수분포

### 균등분포

### t-분포


## 이산형 분포

### 베르누이 분포와 이항분포

### 포아송 분포

### 초기하분포


## 모의실험





# 자료 탐색{#chapter-EDA}

## 일변량 범주형 자료 탐색

### 막대 그래프

### 파이 그래프

### Cleveland의 점 그래프


## 이변량 및 다변량 범주형 자료 탐색

### 분할표 작성

### 이변량 및 다변량 범주형 자료를 위한 그래프


## 일변량 연속형 자료 탐색

### 줄기-잎 그림

### 상지그림

### 히스토그램

### 확률밀도함수 그래프

### 기타 유용한 그래프

### 일변량 연속형 자료의 요약통계


## 이변량 연속형 자료 탐색

### 연속형 변수의 분포를 비교하기 위한 그래프

### 연속형 변수의 관계 탐색을 위한 그래프





# 통계적 추론{#chapter-inference}

## 단일 모집단의 모평균에 대한 검정 및 신뢰구간 추정

## 두 모집단의 모평균 차이에 대한 검정 및 신뢰구간 추정

### 독립된 두 표본에 대한 추론

### 짝을 이룬 표본에 대한 추론

## 단일 모집단의 모비율에 대한 검정 및 신뢰구간 추정

## 두 모집단의 모비율 차이에 대한 검정 및 신뢰구간 추정

## 두 범주형 변수의 독립성 검정

### 카이제곱 독립성 검정

### Fisher의 정확검정

## 정규겅 검정

### 검정에 의한 정규성 확인

### 그래프에 의한 정규성 확인

## 단일 모집단의 분포 중심에 대한 비모수 검정

## 두 모집단의 분포 중심 차이에 대한 비모수 검정





# 선형회귀모형{#chapter-regression}

## 회귀모형의 적합

## 회귀모형의 추론

## 변수선택

## 회귀진단

### 회귀모형의 가정 만족 여뷰 확인

### 특이한 관찰값 탐지

### 대안 탐색

## 예측

## `broom`의 활용



# 로지스틱 회귀모형{#chapter-logistic}

## 이항반응변수에 대한 선형회귀모형의 한계

## 로지스틱 회귀모형의 적합

### 모형 적합

### 확률 예측

## 변수선택

## 회귀진단

## 분류성능 평가

## 희귀사건 분류

