--- 
title: "R과 통계분석"
author: "박동련"
date: "`r Sys.Date()`"
output:
  bookdown::gitbook: default
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
---

# 소개하기 {.unnumbered}

```{r include=FALSE}
knitr::opts_chunk$set(prompt=TRUE, comment = NULL, collapse = TRUE, message=FALSE, fig.width=6, fig.height=4)
```

R은 통계분석과 그래프 작성 및 통계적 프로그래밍에 적합한 매우 효과적인 분석 도구입니다. 
또한 R은 잠시도 정체되어 있지 않고 끊임없이 진화하고 있으며, 
놀라운 발전 속도를 항상 보여주고 있습니다. 
특히 패키지 `tidyverse`의 출현은 매우 주목할 사항입니다. 
그것은 R의 모습이 `tidyverse` 이전과 이후로 완전히 구분된다고 할 수 있기 때문입니다. 
데이터 다루기와 그래프 성능이 비교할 수 없을 만큼 향상되었고, 복잡한 분석 과정이 대폭 단순화되어 매우 효율적인 분석이 가능해졌습니다. 
이러한 발전으로 인하여 R은 이제 data science를 위한 최적의 프로그램으로 자리매김을 확고하게 했다고 할 수 있습니다.

이 책은 R을 처음 접하는 초급 사용자에게 R의 특징을 소개하는 것뿐만이 아니라 이미 R을 사용하고 있는 중급 사용자에게 실질적인 도움이 될 수 있도록 구성되어 있습니다
1장에서 \@ref(chapter-ggplot2)장까지는 초급 사용자를 위해 R의 기본 개념에 대한 설명을 시작으로 해서, 
패키지 `readr` 등을 활용한 외부 데이터 불러오기, `dplyr`에 의한 데이터 다듬기 및 `ggplot2`의 기본 개념을 소개하고 있습니다. 
\@ref(ch6)장부터 \@ref(chapter-EDA)장까지는 중급 사용자를 위해 `tidyr`에 의한 데이터 변형, `dplyr`에 의한 자료 결합, `stringr`에 의한 문자 다루기 및 `purrr`에 의한 프로그래밍 기법에 대한 소개가 있으며, 데이터 시각화에 의한 자료탐색 과정에 대한 설명이 예제와 함께 잘 소개되어 있습니다. 

R은 data science 분야에서 사용되는 여러 프로그래밍 언어 중에서 가장 뛰어난 통계분석 기능이 있는 언어입니다.
Data scientist가 되기를 원하시는 분들에게 조금이나마 도움이 되기를 바라는 마음에서 이 책을 출간합니다. 

